### PR TITLE
Add technical details to README

### PR DESCRIPTION
**Pull request by contributorpw**
Sometimes my Ubuntu server (with `ru ru` arguments) falls down if I use default `fs.inotify.max_user_watches`.

I'm sure It's `inotify`'s issues.

`sudo sysctl fs.inotify.max_user_watches=524288` is not evil. Even with `sudo`.

If you think this is redundant then just reject the PR.

Thanks!

### CODE REVIEW

**Comment by iliakan** [comment]
Please, move it to troubleshooting.

**Comment by oshliaer** [comment]
@iliakan , done.

**Comment by lex111** [comment]
ping @iliakan

**Comment by iliakan** [comment]
What's the error name? How people know that `inotify` is the reason?

**Comment by contributorpw** [comment]
Hi there!

Sorry I missed this.

I was catching `Error: ENOSPC` irregularly while testing the server and edit the js-book.

I have to run this one more time and reset my settings to log the exact stack. Please wait.

**Pull request merged**
